"""Local filesystem storage backend (V1).

Security notes (vision.txt §11 — path traversal):
* Storage keys are generated by the server and validated against a strict
  structure before any path is derived from them. User input never reaches
  this module.
* File writes are atomic: data goes to a temp file in the same directory and
  is `os.replace`d into place, so a crash can never leave a partial file
  referenced by a committed database row.
"""

import os
import tempfile
from typing import BinaryIO

from .interface import StorageError, validate_key


class LocalStorage:
    """Stores validated note files under a configurable root directory."""

    def __init__(self, root_dir: str) -> None:
        self._root = os.path.abspath(root_dir)

    def _resolve(self, key: str) -> str:
        validate_key(key)
        path = os.path.abspath(os.path.join(self._root, key))
        # Defense in depth: even a hypothetical bad key must stay in the root.
        if not path.startswith(self._root + os.sep):
            raise StorageError("storage key escapes storage root")
        return path

    def save(self, key: str, fileobj: BinaryIO) -> None:
        path = self._resolve(key)
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            # Write to a temp file in the same directory, then atomically move.
            fd, tmp_path = tempfile.mkstemp(dir=os.path.dirname(path), suffix=".tmp")
            try:
                with os.fdopen(fd, "wb") as tmp:
                    while chunk := fileobj.read(1024 * 1024):
                        tmp.write(chunk)
                os.replace(tmp_path, path)
            except BaseException:
                if os.path.exists(tmp_path):
                    os.unlink(tmp_path)
                raise
        except OSError as exc:
            raise StorageError(f"failed to store file: {exc}") from exc

    def open(self, key: str) -> BinaryIO:
        path = self._resolve(key)
        try:
            return open(path, "rb")
        except FileNotFoundError as exc:
            raise StorageError("stored file is missing") from exc
        except OSError as exc:
            raise StorageError(f"failed to open file: {exc}") from exc

    def delete(self, key: str) -> None:
        path = self._resolve(key)
        try:
            os.unlink(path)
        except FileNotFoundError:
            return  # idempotent
        except OSError as exc:
            raise StorageError(f"failed to delete file: {exc}") from exc
